services:
  api: 
    build: .
    volumes:
      - .:/app
    ports:
      - ${PORT}:${PORT}
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - my-mongodb
      - redis
  my-mongodb:
    image: mongo:4.2.3-bionic
    container_name: my-mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=quizs
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      # seeding scripts
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      # named volumes
      - mongodb:/data/db
      - mongoconfig:/data/configdb
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_AOF_ENABLED=no
    ports:
      - '6379:6379'
    volumes:
      - 'redis-persistence:/bitnami'
volumes:
  # default dir on Ubuntu: /var/lib/docker/volumes
  mongodb:
  mongoconfig:
  redis-persistence:
